### ISSUE TITLE
Link to paper

### ISSUE THREAD

**Issue by UndecidedBoy** [zhanglichao/end2end_rgbt_tracking#1]
Hello,

I wanted to read your paper _**"Multi-modal fusion for end-to-end RGB-T tracking"**_ but the link provided to the paper is actually pointing to your other paper _**"Learning the Model Update for Siamese Trackers"**_.

Regards!

**Comment by zhanglichao** [comment]
Hi,

Yes, now it's a temporary link. We're planning to upload to it this month.
Thanks for your interests. 

best,
Lichao

**Comment by UndecidedBoy** [comment]
I'm looking forward to reading your paper! :)
