### ISSUE TITLE
Broken pre-trained model?

### ISSUE THREAD

**Issue by LouisShen233** [zhanglichao/end2end_rgbt_tracking#3]
I downloaded the pre-trained model but it couldn't be unzipped. The error information showed the system couldn't recognize it. 

Maybe something missing when it was uploaded?
Thank you for your time.

**Comment by zhanglichao** [comment]
Hi,

The model should be in the format of pytorch, where it can be import directly. You should not unzip it.

Best,
lichao

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Louisshen <notifications@github.com>
发送时间: Wednesday, March 18, 2020 3:11:34 AM
收件人: zhanglichao/end2end_rgbt_tracking <end2end_rgbt_tracking@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [zhanglichao/end2end_rgbt_tracking] Broken pre-trained model? (#3)


I downloaded the pre-trained model but it couldn't be unzipped. The error information showed the system couldn't recognize it.

Maybe something missing when it was uploaded?
Thank you for your time.

―

**Comment by LouisShen233** [comment]
Got it. Thank you.
